#######################################################################
# Copyright (C)2012, International Business Machines Corporation and
# others. All Rights Reserved.
#######################################################################

all: mctsLib
	spl-make-toolkit -m -i .
	
clean:
	cd impl; make clean
	
mctsLib:
	cd impl; make all
	
mctsLibClean:
	cd impl; make clean	
	
	
	
	

